import 'package:albazar_app/core/utils/icons.dart';
import 'package:albazar_app/core/widgets/custom_drob_down.dart';

class AppConstants {
  const AppConstants._();

  static List<String> cityLists = [
    'دمشق',
    ' ريف دمشق',
    'القنيطرة',
    'درعا',
    'السويداء',
    'حمص',
    'طرطوس',
    'اللاذقية',
    'حماة',
    'إدلب',
    'حلب',
    'الرقة',
    'دير الزور',
    'الحسكة',
  ];

  static const List<String> carBrands = [
    "أوبل",
    "أودي",
    "ألتيما",
    "أنفينيتي",
    "أيسوزو",
    "أولدزموبيل",
    "أوستن مارتن",
    "ألفا روميو",
    "أسيا",
    "إم جي",
    "بايك",
    "باربوس",
    "بريليانس",
    "برودوا",
    "بروتون",
    "بلايموث",
    "بنتلي",
    "بوغاتي",
    "بويك",
    "بي إم دبليو",
    "بيجو",
    "بي واي دي",
    "تاتا",
    "تاترا",
    "تويوتا",
    "جاك",
    "جاكوار",
    "جي أم سي",
    "جينيسيس",
    "جينبي",
    "جيب",
    "جوندا",
    "جيلي",
    "جي أم سي",
    "حميشو",
    "دايو",
    "دايهاتسو",
    "داتسون",
    "داسيا",
    "دوماى",
    "دودج",
    "دونغ فينج",
    "دى إف إم",
    "رانج روفر",
    "روفر",
    "روفي",
    "رولز رايس",
    "رينو",
    "رينو سامسونج",
    "زوتاي",
    "زاز",
    "زد اكس",
    "سامسونج",
    "سايبا",
    "سانج يونج",
    "سبرينتر",
    "سيتروين",
    "سيا",
    "سيت",
    "سيات",
    "سيريس",
    "سوزوكي",
    "سوبارو",
    "سكودا",
    "سمارت",
    "سما",
    "ساب",
    "شاهين",
    "شاحنة صغيرة",
    "شانا",
    "شانجان",
    "شانغ فينغ",
    "شانجى",
    "شام",
    "شيري",
    "شيفروليه",
    "صنى",
    "طوكيو",
    "فاو",
    "فورد",
    "فوكس فاكن",
    "فولفو",
    "فيراري",
    "فيات",
    "فينغ",
    "كاديلاك",
    "كاما",
    "كرايسلر",
    "كيا",
    "لادا",
    "لابمرغيني",
    "لانسيا",
    "لاندروفر",
    "لاندويند",
    "لكزس",
    "ليونسيل",
    "ليفان",
    "لينكولن",
    "لوتوس",
    "ماروتي",
    "مازاراتى",
    "مازدا",
    "ماي باخ",
    "ميتسوبيشي",
    "ميركوري",
    "ميني كوبر",
    "نيسان",
    "هافال",
    "هايما",
    "هافي ميني",
    "هامر",
    "هوندا",
    "هيونداي"
  ];
  static List<CarModel> cars = [
    CarModel(name: 'أوبل', image: CarsLogo.opel),
    CarModel(name: 'أودي', image: CarsLogo.audit),
    CarModel(name: 'أنفينيتي', image: CarsLogo.infiniti),
    CarModel(name: 'أيسوزو', image: CarsLogo.isuzu),
    CarModel(name: 'أولدزموبيل', image: CarsLogo.oldsmobile),
    CarModel(name: 'أوستن مارتن', image: CarsLogo.astonmartin),
    CarModel(name: 'ألفا روميو', image: CarsLogo.alfaRomeo),
    CarModel(name: 'أسيا', image: CarsLogo.asia),
    CarModel(name: 'إم جي', image: CarsLogo.mg),
    CarModel(name: 'بايك', image: CarsLogo.baic),
    CarModel(name: 'بريليانس', image: CarsLogo.brilliance),
    CarModel(name: 'برودوا', image: CarsLogo.perodua),
    CarModel(name: 'بروتون', image: CarsLogo.bertone),
    CarModel(name: 'بلايموث', image: CarsLogo.plymouth),
    CarModel(name: 'بنتلي', image: CarsLogo.bentley),
    CarModel(name: 'بوغاتي', image: CarsLogo.bugatti),
    CarModel(name: 'بويك', image: CarsLogo.bac),
    CarModel(name: 'بي إم دبليو', image: CarsLogo.bmw),
    CarModel(name: 'بيجو', image: CarsLogo.peugeot),
    CarModel(name: 'بي واي دي', image: CarsLogo.byd),
    CarModel(name: 'تاتا', image: CarsLogo.tata),
    CarModel(name: 'تاترا', image: CarsLogo.tatra),
    CarModel(name: 'تويوتا', image: CarsLogo.toyota),
    CarModel(name: 'جاك', image: CarsLogo.jacMotors),
    CarModel(name: 'جاكوار', image: CarsLogo.jaguar),
    CarModel(name: 'جينيسيس', image: CarsLogo.genesis),
    CarModel(name: 'جينبي', image: CarsLogo.ginetta),
    CarModel(name: 'جيب', image: CarsLogo.jeep),
    CarModel(name: 'جيلي', image: CarsLogo.geely),
    CarModel(name: 'جي أم سي', image: CarsLogo.gmc),
    CarModel(name: 'دايو', image: CarsLogo.daewoo),
    CarModel(name: 'دايهاتسو', image: CarsLogo.daihatsu),
    CarModel(name: 'داتسون', image: CarsLogo.datsun),
    CarModel(name: 'داسيا', image: CarsLogo.dacia),
    CarModel(name: 'دودج', image: CarsLogo.dodge),
    CarModel(name: 'دونغ فينج', image: CarsLogo.dongfeng),
    CarModel(name: 'لاند روفر', image: CarsLogo.landRover),
    CarModel(name: 'روفي', image: CarsLogo.ruf),
    CarModel(name: 'رولز رايس', image: CarsLogo.rolls),
    CarModel(name: 'رينو', image: CarsLogo.renault),
    CarModel(name: 'رينو سامسونج', image: CarsLogo.samsung),
    CarModel(name: 'زوتاي', image: CarsLogo.zotye),
    CarModel(name: 'زاز', image: CarsLogo.zaz),
    CarModel(name: 'سايبا', image: CarsLogo.saipa),
    CarModel(name: 'سانج يونج', image: CarsLogo.suangYong),
    CarModel(name: 'سيتروين', image: CarsLogo.citroen),
    CarModel(name: 'سيات', image: CarsLogo.seat),
    CarModel(name: 'سوزوكي', image: CarsLogo.suzuki),
    CarModel(name: 'سوبرا', image: CarsLogo.subaru),
    CarModel(name: 'سكودا', image: CarsLogo.skoda),
    CarModel(name: 'سمارت', image: CarsLogo.smart),
    CarModel(name: 'ساب', image: CarsLogo.saab),
    CarModel(name: 'شانجان', image: CarsLogo.changan),
    CarModel(name: 'شانغ فينغ', image: CarsLogo.changfeng),
    CarModel(name: 'شيري', image: CarsLogo.chery),
    CarModel(name: 'شيفروليه', image: CarsLogo.chevrolet),
    CarModel(name: 'نيسان', image: CarsLogo.nissan),
    CarModel(name: 'فاو', image: CarsLogo.faw),
    CarModel(name: 'فورد', image: CarsLogo.ford),
    CarModel(name: 'فولفو', image: CarsLogo.volvo),
    CarModel(name: 'فيراري', image: CarsLogo.ferrari),
    CarModel(name: 'فيات', image: CarsLogo.fiat),
    CarModel(name: 'كاما', image: CarsLogo.camco),
    CarModel(name: 'كيا', image: CarsLogo.kia),
    CarModel(name: 'لادا', image: CarsLogo.lada),
    CarModel(name: 'لابمرغيني', image: CarsLogo.lamborghini),
    CarModel(name: 'لانسيا', image: CarsLogo.lancia),
    CarModel(name: 'لاندويند', image: CarsLogo.landwind),
    CarModel(name: 'لكزس', image: CarsLogo.lexus),
    CarModel(name: 'لوتوس', image: CarsLogo.lotus),
    CarModel(name: 'مازاراتي', image: CarsLogo.maserati),
    CarModel(name: 'مازدا', image: CarsLogo.mazda),
    CarModel(name: 'ماي باخ', image: CarsLogo.maybach),
    CarModel(name: 'ميتسوبيشي', image: CarsLogo.mitsubishi),
    CarModel(name: 'ميركوري', image: CarsLogo.mercury),
    CarModel(name: 'ميني كوبر', image: CarsLogo.mini),
    CarModel(name: 'هافال', image: CarsLogo.haval),
    CarModel(name: 'هايما', image: CarsLogo.haima),
    CarModel(name: 'هامر', image: CarsLogo.hummer),
    CarModel(name: 'هوندا', image: CarsLogo.honda),
    CarModel(name: 'هيونداي', image: CarsLogo.hyundai),
    CarModel(name: 'الفوكس فاكن', image: CarsLogo.volkan),
  ];
}
